```{r}
data1$TVhours


```

```{r}
as.character(data1$TVhours)
```

```{r}
as.numeric(as.character(data1$TVhours))
```

```{r}
typeof(as.numeric(as.character(data1$TVhours)))
```

```{r}
tv.hours.strings <- as.character(data1$TVhours)
tv.hours.strings
```
```{r}
gsub("[^0-9].","",data1$TVhours)
```

```{r}
colnames(birthwt) <- c("birthwt.below.2500","monther.age","mother.weight","race","mother.smokes","previous.prem.labor","hypertension","uterine.irr","physician.visits","birthwt.grams")

birthwt <- transform(birthwt,
                      race = as.factor(mapvalues(race,c(1,2,3),c("white","black","other"))),
                      mother.smokes = as.factor(mapvalues(mother.smokes,c(0,1),c("no","yes"))),
                      hypertension = as.factor(mapvalues(hypertension,c(0,1),c("no","yes"))),
                      uterine.irr = as.factor(mapvalues(uterine.irr,c(0,1),c("no","yes")))
                      )


phys.visit.binned <- birthwt$physician.visits
phys.visit.binned[phys.visit.binned >=3] <- "3.or.more"
birthwt <- transform(birthwt,phys.visit.binned = as.factor(phys.visit.binned))

birthwt$phys.visit.binned

```

```{r}
diamonds.plot <- ggplot(data=diamonds, aes(x=carat,y=price,colour = color))
diamonds.plot + geom_point() + facet_grid(cut ~ .)
```

```{r}
library(rvest)
test_movie <- read_html("http://www.imdb.com/title/tt1490017/")
test_movie %>%
  html_nodes("strong span") %>%
  html_text() %>%
  as.numeric()
```
```{r}
test_movie %>%
  html_nodes("#titleCast .itemprop span") %>%
  html_text()
```

```{r}
aov.birthwt <- aov(birthwt.grams ~ phys.visit.binned,data = birthwt)
summary(aov.birthwt)
```
```{r}
birthwt.lm <- lm(birthwt.grams ~ monther.age + mother.smokes, data = birthwt)
summary(birthwt.lm)
```

